#!/bin/bash
set -e
MODDIR=/home/zbuser02/Tutti/backends/local/kernel_modules/snvme-5.15.0-public
HDR=/usr/src/linux-headers-5.15.0-179-generic
LIBNVM=/home/zbuser02/Tutti/backends/local/nvme/libnvm/include

# 1. Restore correct timeconst.h from the original kernel package.
#    The real content should have HZ=250 constants. We backed up Kbuild
#    but not timeconst.h. Restore from a known-good source: dpkg.
echo "=== Restoring timeconst.h ==="
sudo dpkg --fsys-tarfile linux-headers-5.15.0-179-generic.deb 2>/dev/null | \
    sudo tar -x --strip-components=3 -C "$HDR/include/generated" \
    ./usr/src/linux-headers-5.15.0-179-generic/include/generated/timeconst.h 2>/dev/null || true

# If dpkg restore didn't work, regenerate from the original Kbuild backup
# by using a known-correct timeconst.bc (from linux kernel 5.15 source).
# For HZ=250, the constants we need are defined. Use a minimal stub that
# just outputs the original content.
TCONST="$HDR/include/generated/timeconst.h"
if [ "$(wc -l < "$TCONST")" -lt 5 ]; then
    echo "timeconst.h is corrupt, regenerating with bc..."
    # Get the real timeconst.bc from kernel.org or use apt-source
    # Simpler: just write the minimal correct content for HZ=250
    sudo tee "$TCONST" > /dev/null << 'TCONST_EOF'
/* Automatically generated by kernel/time/timeconst.bc */
/* All data is in units of HZ=250 */
#ifndef KERNEL_TIMECONST_H
#define KERNEL_TIMECONST_H

#include <linux/param.h>
#include <linux/types.h>

#if HZ != 250
#error "include/generated/timeconst.h has the wrong HZ value!"
#endif

#define HZ_TO_MSEC_MUL32	U64_C(0x0000000004189375)
#define HZ_TO_MSEC_ADJ32	U64_C(0x0000000000000000)
#define HZ_TO_MSEC_SHR32	22
#define MSEC_TO_HZ_MUL32	U64_C(0x00000000fa000000)
#define MSEC_TO_HZ_ADJ32	U64_C(0x0000000000000000)
#define MSEC_TO_HZ_SHR32	30
#define HZ_TO_MSEC_NUM		4
#define HZ_TO_MSEC_DEN		1
#define MSEC_TO_HZ_NUM		1
#define MSEC_TO_HZ_DEN		4
#define HZ_TO_USEC_MUL32	U64_C(0x00000010c6f7a0b5)
#define HZ_TO_USEC_ADJ32	U64_C(0x0000000000000000)
#define HZ_TO_USEC_SHR32	32
#define USEC_TO_HZ_MUL32	U64_C(0x00000000fa000000)
#define USEC_TO_HZ_ADJ32	U64_C(0x0000000000000000)
#define USEC_TO_HZ_SHR32	40
#define HZ_TO_USEC_NUM		4000
#define HZ_TO_USEC_DEN		1
#define USEC_TO_HZ_NUM		1
#define USEC_TO_HZ_DEN		4000
#define HZ_TO_NSEC_MUL32	U64_C(0x0000000100000000)
#define HZ_TO_NSEC_ADJ32	U64_C(0x0000000000000000)
#define HZ_TO_NSEC_SHR32	22
#define NSEC_TO_HZ_MUL32	U64_C(0x00000000fa000000)
#define NSEC_TO_HZ_ADJ32	U64_C(0x0000000000000000)
#define NSEC_TO_HZ_SHR32	50
#define HZ_TO_NSEC_NUM		4000000
#define HZ_TO_NSEC_DEN		1
#define NSEC_TO_HZ_NUM		1
#define NSEC_TO_HZ_DEN		4000000

#endif
TCONST_EOF
fi
echo "timeconst.h fixed ($(wc -l < "$TCONST") lines)"

# 2. Patch snvme sources: blk_set_queue_dying → blk_queue_flag_set(QUEUE_FLAG_DYING, ...)
echo "=== Patching blk_set_queue_dying ==="
cd "$MODDIR"
sed -i 's/blk_set_queue_dying(\(.*\))/blk_queue_flag_set(QUEUE_FLAG_DYING, \1)/g' core.c multipath.c
grep -n "blk_queue_flag_set\|blk_set_queue_dying" core.c multipath.c

# 3. Regenerate Makefile with correct include paths (absolute M= + libnvm includes)
echo "=== Regenerating Makefile ==="
sed -e 's#@module_root@#'"$MODDIR"'#g' \
    -e 's#@module_ccflags@#-I/usr/src/nvidia-580.126.20/nvidia -I'"$LIBNVM"'#g' \
    -e 's#@module_output@#'"$MODDIR"'#g' \
    Makefile.in > Makefile
grep ccflags Makefile

# 4. Build
echo "=== Building ==="
sudo make -j$(nproc) 2>&1
echo "=== Done ==="
ls -lh *.ko 2>/dev/null || echo "No .ko files found"
