#!/usr/bin/env bash
set -euo pipefail

base=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
mode="${1:-on}"
if [[ "$mode" != "on" && "$mode" != "off" ]]; then
  echo "usage: $0 [on|off]" >&2
  exit 2
fi

LMCACHE_ABLATION_IMAGE=lmcache/csa-prefetch:protected-1p491-20260727 \
LMCACHE_ABLATION_PATCH_DIR="$base/patches" \
LMCACHE_ABLATION_STARTUP_SCRIPT="$base/startup_cp8_ab.sh" \
LMCACHE_ABLATION_MODEL_HOST=/mnt/dockerdisk/models/DeepSeek-V4-flash \
LMCACHE_ABLATION_MAX_MODEL_LEN=530000 \
LMCACHE_ABLATION_MAX_BATCHED_TOKENS=65536 \
LMCACHE_ABLATION_GPU_UTIL=0.55 \
LMCACHE_ABLATION_TUTTI_STARTUP_DELAY="${LMCACHE_ABLATION_TUTTI_STARTUP_DELAY:-120}" \
LMCACHE_ABLATION_TUTTI_AFTER_STORE_DELAY=10 \
LMCACHE_CSA_PREFETCH_LOOKAHEAD_BY_LAYER=profile80_hybrid \
LMCACHE_CSA_PREFETCH_CP_SIZE=8 \
LMCACHE_CSA_PREFETCH_CP_INTERLEAVE=64 \
LMCACHE_CSA_PREFETCH_CP_OVERSUBSCRIBE=1 \
LMCACHE_CSA_PREFETCH_CP_EXCHANGE_IDS=1 \
LMCACHE_CSA_PREFETCH_BLOCK_BUDGET=2048 \
LMCACHE_CSA_L1_PROXY_TOPK_TOKENS=2048 \
LMCACHE_CSA_PROXY_TOPK_TOKENS_BY_LAYER=28:2048 \
LMCACHE_INDEXER_PROFILE_ACCURACY="${LMCACHE_INDEXER_PROFILE_ACCURACY:-1}" \
LMCACHE_CSA_PREDICTION_GATE_TIMEOUT_SEC=5 \
LMCACHE_NATIVE_INDEXER_STAGE0_LAYERS=1 \
LMCACHE_NATIVE_INDEXER_WINDOW_LAYERS=1 \
LMCACHE_SSD_TP_SHARDED_PREFETCH=1 \
LMCACHE_SSD_TP_SHARD_INDEXER=0 \
LMCACHE_SSD_TP_SHARD_CSA=1 \
LMCACHE_SSD_TP_CSA_REPLICA_VERIFIED=1 \
LMCACHE_SSD_TP_INDEXER_CP_VERIFIED=0 \
LMCACHE_SSD_TP_CP_SIZE=8 \
LMCACHE_SSD_TP_CP_INTERLEAVE=64 \
LMCACHE_SSD_TP_DENSE_LAYERS=2-24 \
LMCACHE_SSD_TP_MIN_UNION_BLOCKS=128 \
LMCACHE_SSD_TP_STAGING_SLOT_BYTES=134217728 \
LMCACHE_SSD_TP_STAGING_SLOTS=2 \
LMCACHE_SSD_TP_EARLY_LOOKAHEAD=2 \
LMCACHE_SSD_TP_DEBUG_VERIFY="${LMCACHE_SSD_TP_DEBUG_VERIFY:-1}" \
LMCACHE_INDEXER_TIMING="${LMCACHE_INDEXER_TIMING:-1}" \
LMCACHE_CSA_ATTENTION_KV_TIMING="${LMCACHE_CSA_ATTENTION_KV_TIMING:-1}" \
LMCACHE_TTFT_STAGE_PROFILE="${LMCACHE_TTFT_STAGE_PROFILE:-1}" \
LMCACHE_LOOKUP_TOKEN_DIAGNOSTICS="${LMCACHE_LOOKUP_TOKEN_DIAGNOSTICS:-1}" \
LMCACHE_NSYS_CAPTURE=0 \
LMCACHE_NSYS_FULL_CAPTURE=0 \
LMCACHE_TUTTI_PROFILE="${LMCACHE_TUTTI_PROFILE:-0}" \
bash "$base/run_container_cp8_ab.sh" "$mode"
