#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail

mode=${1:-ours}
if [[ ${mode} != ours ]]; then
  echo "V4-Pro final launcher supports only ours, got: ${mode}" >&2
  exit 2
fi

root=${LMCACHE_V026_RUN_ROOT:-/home/zbuser02/lmcache_v026_20260806_run}
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
version_dir=${LMCACHE_MATRIX_VERSION_DIR:-${script_dir}}
model=${LMCACHE_ABLATION_MODEL_HOST:-/local/DeepSeek-V4-Pro-HF64}
overlay=${LMCACHE_ABLATION_PATCH_DIR:-${version_dir}/pro_cp_workspace_overlay}
startup=${LMCACHE_ABLATION_STARTUP_SCRIPT:-${version_dir}/startup_cp8_ab.sh}
max_model_len=${LMCACHE_ABLATION_MAX_MODEL_LEN:-1048576}
max_batched_tokens=${LMCACHE_ABLATION_MAX_BATCHED_TOKENS:-8192}

if [[ ! -f ${model}/config.json ]]; then
  echo "missing V4-Pro checkpoint: ${model}/config.json" >&2
  exit 2
fi

LMCACHE_ABLATION_IMAGE="${LMCACHE_ABLATION_IMAGE:-lmcache/vllm-openai:v0.26.0-lmcache0.5.2-official}" \
LMCACHE_ABLATION_PATCH_DIR="${overlay}" \
LMCACHE_ABLATION_STARTUP_SCRIPT="${startup}" \
LMCACHE_ABLATION_MODEL_HOST="${model}" \
LMCACHE_STORAGE_MODE=tutti \
LMCACHE_SSD_LOCAL_CPU_GB=16 \
LMCACHE_SSD_DSV4_OPTIMIZED_KV=true \
LMCACHE_SSD_DSV4_OPTIMIZED_TAIL_TOKENS=256 \
LMCACHE_SSD_DSV4_DEFER_HCA_TO_MOE=false \
LMCACHE_ABLATION_MAX_MODEL_LEN="${max_model_len}" \
LMCACHE_ABLATION_MAX_BATCHED_TOKENS="${max_batched_tokens}" \
LMCACHE_ABLATION_GPU_UTIL="${LMCACHE_ABLATION_GPU_UTIL:-0.85}" \
VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS="${VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS:-1200}" \
LMCACHE_ABLATION_KV_OBJECT_STORE_SLOT_MB=8 \
LMCACHE_ABLATION_KV_OBJECT_STORE_CAPACITY="${LMCACHE_ABLATION_KV_OBJECT_STORE_CAPACITY:-120000}" \
LMCACHE_TUTTI_RAW_REGION_BYTES="${LMCACHE_TUTTI_RAW_REGION_BYTES:-2199023255552}" \
LMCACHE_INDEXER_RAW_REGION_BYTES="${LMCACHE_INDEXER_RAW_REGION_BYTES:-68719476736}" \
LMCACHE_ABLATION_TUTTI_N_SLOTS="${LMCACHE_ABLATION_TUTTI_N_SLOTS:-8}" \
LMCACHE_ABLATION_TUTTI_SLOT_MB="${LMCACHE_ABLATION_TUTTI_SLOT_MB:-16}" \
LMCACHE_ABLATION_TUTTI_STARTUP_DELAY=1 \
LMCACHE_ABLATION_TUTTI_AFTER_STORE_DELAY=10 \
LMCACHE_CSA_PREFETCH_LOOKAHEAD_BY_LAYER="${LMCACHE_CSA_PREFETCH_LOOKAHEAD_BY_LAYER:-default:2,54:1,60:1}" \
LMCACHE_CSA_PREFETCH_CP_SIZE=8 \
LMCACHE_CSA_PREFETCH_CP_INTERLEAVE=64 \
LMCACHE_CSA_PREFETCH_CP_OVERSUBSCRIBE=1 \
LMCACHE_CSA_PREFETCH_CP_MODE="${LMCACHE_CSA_PREFETCH_CP_MODE:-key_sharded_owner}" \
LMCACHE_CSA_OWNER_BLOCKS_PER_RANK="${LMCACHE_CSA_OWNER_BLOCKS_PER_RANK:-512}" \
LMCACHE_CSA_PREDICTION_DENSIFY_PERCENT=0 \
LMCACHE_CSA_PROPAGATE_TOPK_LAYERS=0 \
LMCACHE_CSA_PREFETCH_CP_QUERY_SAMPLE_STRIDE=1 \
LMCACHE_CSA_PREFETCH_CP_EXCHANGE_IDS=1 \
LMCACHE_CSA_PREFETCH_CP_GLOBAL_BLOCK_COUNTS=0 \
LMCACHE_CSA_PREFETCH_CP_GLOBAL_BLOCK_BITMAP=0 \
LMCACHE_CSA_PROXY_HC_PREWARM_ROWS='64,128,160,256,448,512,1024' \
LMCACHE_CSA_PREFETCH_BLOCK_BUDGET=2048 \
LMCACHE_CSA_L1_PROXY_TOPK_TOKENS=512 \
LMCACHE_CSA_PROXY_TOPK_TOKENS_BY_LAYER='' \
LMCACHE_DSV4_HCA_WALKER=0 \
LMCACHE_HCA_PREFIRE_FIRST_LAYER=1 \
LMCACHE_NATIVE_INDEXER_STAGE0_LAYERS=1 \
LMCACHE_NATIVE_INDEXER_WINDOW_LAYERS=1 \
LMCACHE_SSD_TP_SHARDED_PREFETCH=1 \
LMCACHE_SSD_TP_SHARD_INDEXER=0 \
LMCACHE_SSD_TP_SHARD_CSA=1 \
LMCACHE_SSD_TP_CSA_REPLICA_VERIFIED=1 \
LMCACHE_SSD_TP_INDEXER_CP_VERIFIED=0 \
LMCACHE_SSD_TP_CP_SIZE=8 \
LMCACHE_SSD_TP_CP_INTERLEAVE=64 \
LMCACHE_SSD_TP_DENSE_LAYERS='' \
LMCACHE_SSD_TP_DENSE_EAGER_GROUP_SIZE=4 \
LMCACHE_SSD_TP_MIN_UNION_BLOCKS=128 \
LMCACHE_SSD_TP_LOCAL_DIRECT_COVERAGE_RATIO=0 \
LMCACHE_SSD_TP_EARLY_COLLECTIVE=0 \
LMCACHE_SSD_TP_DENSE_EARLY_COLLECTIVE=0 \
LMCACHE_SSD_TP_COLLECTIVE_STREAM_PRIORITY=0 \
LMCACHE_SSD_TP_STAGING_SLOT_BYTES="${LMCACHE_SSD_TP_STAGING_SLOT_BYTES:-268435456}" \
LMCACHE_SSD_TP_STAGING_SLOTS=2 \
LMCACHE_SSD_TP_EARLY_LOOKAHEAD=2 \
LMCACHE_TRUE_INDEXER_CP=0 \
LMCACHE_TRUE_INDEXER_CP_SIZE=8 \
LMCACHE_TRUE_INDEXER_CP_MIN_ROWS=1024 \
LMCACHE_DSV4_STREAMING_PLAN_CACHE_CAPACITY=64 \
LMCACHE_DSV4_STREAMING_PLAN_PREBUILD=1 \
LMCACHE_DSV4_STATIC_IO_GROUP_MAX=8 \
LMCACHE_DSV4_STATIC_IO_GROUP_TARGET_MIB=32 \
LMCACHE_DSV4_RAW_WRITE_WAVE_MB=256 \
LMCACHE_PIN_TP_NUMA=1 \
LMCACHE_PY_ENABLE_GC=false \
LMCACHE_WRITE_SLACK_API_ENABLED=true \
LMCACHE_TOOL_SLACK_HOOK=1 \
LMCACHE_TUTTI_BACKGROUND_WRITE_MIBPS=0 \
LMCACHE_TUTTI_BACKGROUND_WRITE_BURST_MIB=8 \
LMCACHE_TUTTI_PAUSE_WRITES_DURING_DECODE=0 \
LMCACHE_TUTTI_DECODE_WRITE_GUARD_S=2 \
LMCACHE_INDEXER_PROFILE_ACCURACY=0 \
LMCACHE_INDEXER_TIMING=0 \
LMCACHE_CSA_ATTENTION_KV_TIMING=0 \
LMCACHE_TTFT_STAGE_PROFILE=0 \
LMCACHE_LOOKUP_TOKEN_DIAGNOSTICS=0 \
LMCACHE_D2H_TIMING=0 \
LMCACHE_HCA_TIMING=0 \
LMCACHE_NSYS_CAPTURE=0 \
LMCACHE_NSYS_FULL_CAPTURE=0 \
LMCACHE_TUTTI_PROFILE=0 \
LMCACHE_ALLOW_OVERSIZED_KV_CACHE=1 \
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False \
bash "${version_dir}/run_container_cp8_ab.sh" on
