#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail

root=${LMCACHE_V026_RUN_ROOT:-/home/zbuser02/lmcache_v026_20260806_run}
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
version_dir=${LMCACHE_MATRIX_VERSION_DIR:-${script_dir}}
model=${LMCACHE_ABLATION_MODEL_HOST:-/local/GLM-5.2-FP8}
overlay=${LMCACHE_ABLATION_PATCH_DIR:-${version_dir}/pro_cp_workspace_overlay}
startup=${LMCACHE_ABLATION_STARTUP_SCRIPT:-${version_dir}/startup_cp8_ab.sh}

if [[ ! -f ${model}/config.json ]]; then
  echo "missing GLM-5.2 checkpoint: ${model}/config.json" >&2
  exit 2
fi

LMCACHE_ABLATION_IMAGE="${LMCACHE_ABLATION_IMAGE:-lmcache/vllm-openai:v0.26.0-lmcache0.5.2-official}" \
LMCACHE_ABLATION_PATCH_DIR="${overlay}" \
LMCACHE_ABLATION_STARTUP_SCRIPT="${startup}" \
LMCACHE_ABLATION_MODEL_HOST="${model}" \
LMCACHE_STORAGE_MODE=tutti \
LMCACHE_ABLATION_MAX_MODEL_LEN="${LMCACHE_ABLATION_MAX_MODEL_LEN:-278528}" \
LMCACHE_ABLATION_MAX_BATCHED_TOKENS="${LMCACHE_ABLATION_MAX_BATCHED_TOKENS:-16384}" \
LMCACHE_ABLATION_GPU_UTIL="${LMCACHE_ABLATION_GPU_UTIL:-0.82}" \
LMCACHE_ABLATION_KV_CACHE_MEMORY_BYTES="${LMCACHE_ABLATION_KV_CACHE_MEMORY_BYTES:-17179869184}" \
LMCACHE_ABLATION_KV_OBJECT_STORE_SLOT_MB=8 \
LMCACHE_ABLATION_KV_OBJECT_STORE_CAPACITY="${LMCACHE_ABLATION_KV_OBJECT_STORE_CAPACITY:-120000}" \
LMCACHE_TUTTI_RAW_REGION_BYTES="${LMCACHE_TUTTI_RAW_REGION_BYTES:-2199023255552}" \
LMCACHE_INDEXER_RAW_REGION_BYTES="${LMCACHE_INDEXER_RAW_REGION_BYTES:-68719476736}" \
LMCACHE_ABLATION_TUTTI_N_SLOTS=4 \
LMCACHE_ABLATION_TUTTI_SLOT_MB=128 \
LMCACHE_ABLATION_TUTTI_STARTUP_DELAY=1 \
LMCACHE_ABLATION_TUTTI_AFTER_STORE_DELAY=5 \
LMCACHE_GLM_DSA_LAYER_MAJOR=1 \
LMCACHE_GLM_DSA_PREDICTIVE_PREFETCH=1 \
LMCACHE_GLM_DSA_BOOTSTRAP_SOURCE_LAYER=0 \
LMCACHE_GLM_DSA_FULL_LAYER_LOOKAHEAD="${LMCACHE_GLM_DSA_FULL_LAYER_LOOKAHEAD:-2}" \
LMCACHE_GLM_DSA_PHYSICAL_PREDICTION=1 \
LMCACHE_GLM_DSA_EARLY_DENSE_GROUP=0 \
LMCACHE_GLM_DSA_IO_WORKERS=4 \
LMCACHE_GLM_DSA_PREFETCH_BLOCK_BUDGET=4096 \
LMCACHE_GLM_DSA_PREDICT_SHARED_CONSUMERS="${LMCACHE_GLM_DSA_PREDICT_SHARED_CONSUMERS:-staged}" \
LMCACHE_GLM_DSA_GATE_TIMEOUT_SEC=30 \
LMCACHE_GLM_DSA_OWNER_PARTITION="${LMCACHE_GLM_DSA_OWNER_PARTITION:-1}" \
LMCACHE_CSA_OWNER_BLOCKS_PER_RANK="${LMCACHE_CSA_OWNER_BLOCKS_PER_RANK:-64}" \
LMCACHE_SSD_TP_SHARDED_PREFETCH=1 \
LMCACHE_SSD_TP_SHARD_INDEXER=0 \
LMCACHE_SSD_TP_SHARD_CSA=1 \
LMCACHE_SSD_TP_CSA_REPLICA_VERIFIED=1 \
LMCACHE_SSD_TP_INDEXER_CP_VERIFIED=0 \
LMCACHE_SSD_TP_CP_SIZE=8 \
LMCACHE_SSD_TP_DENSE_LAYERS='' \
LMCACHE_SSD_TP_MIN_UNION_BLOCKS=128 \
LMCACHE_SSD_TP_LOCAL_DIRECT_COVERAGE_RATIO=0 \
LMCACHE_SSD_TP_STAGING_SLOT_BYTES="${LMCACHE_SSD_TP_STAGING_SLOT_BYTES:-134217728}" \
LMCACHE_SSD_TP_STAGING_SLOTS=2 \
LMCACHE_DSV4_STREAMING_PLAN_CACHE_CAPACITY=64 \
LMCACHE_DSV4_STREAMING_PLAN_PREBUILD=1 \
LMCACHE_DSV4_STATIC_IO_GROUP_MAX=8 \
LMCACHE_DSV4_STATIC_IO_GROUP_TARGET_MIB=32 \
LMCACHE_PIN_TP_NUMA=1 \
LMCACHE_PY_ENABLE_GC=false \
LMCACHE_TRUE_INDEXER_CP=0 \
LMCACHE_PROXY_INDEXER_CP=1 \
LMCACHE_PROXY_INDEXER_CP_SIZE=8 \
LMCACHE_PROXY_INDEXER_CP_MIN_ROWS=1 \
LMCACHE_PROXY_INDEXER_CP_EXCHANGE=1 \
LMCACHE_INDEXER_PROFILE_ACCURACY=0 \
LMCACHE_GLM_DSA_DECODE_COVERAGE_PROFILE=0 \
LMCACHE_INDEXER_TIMING=0 \
LMCACHE_CSA_ATTENTION_KV_TIMING=0 \
LMCACHE_TTFT_STAGE_PROFILE=0 \
LMCACHE_D2H_TIMING=0 \
LMCACHE_HCA_TIMING=0 \
LMCACHE_NSYS_CAPTURE=0 \
LMCACHE_NSYS_FULL_CAPTURE=0 \
LMCACHE_TUTTI_PROFILE=0 \
LMCACHE_WRITE_SLACK_API_ENABLED=true \
LMCACHE_TOOL_SLACK_HOOK=1 \
LMCACHE_TUTTI_PAUSE_WRITES_DURING_DECODE=0 \
LMCACHE_TUTTI_DECODE_WRITE_GUARD_S=2 \
LMCACHE_ALLOW_OVERSIZED_KV_CACHE=1 \
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False \
bash "${version_dir}/run_container_cp8_ab.sh" off
